### PR TITLE
Google Form Creation 

### PR DESCRIPTION
**Pull request by preetjdp**
Implemented Google Form with Google App Script.

### CODE REVIEW

**Comment by nikhil-thakkar** [comment]
This is Awesome!! Thanks @preetjdp. 🎉 
Apps script now support **Typescript**  and as most of the google products.

Could we refactor the code to use typescript? This [link](https://developers.google.com/apps-script/guides/typescript) will help in refactoring. 

Also we need to track this as a project using [clasp](https://github.com/google/clasp).
This will be following advantages:
1. Organising of the code in scripts directory wherein we will have multiple automation project.
2. We would be able to automate the deployment flow using travis/circleci which will remove the need to manually copy the script in the google's console.

Let me know if you need help in refactoring the code to typescript. 
And sorry 😢 if I missed out the point of using Typescript in the conservation.

Thanks again for all the active contributions/suggestions. 👍

**Comment by preetjdp** [comment]
Cool i'll see what i can come up with!

**Comment by preetjdp** [comment]
Decline this PULL request I'll create a new one with clasp and TS

**Comment by preetjdp** [comment]
@nikhil-thakkar I've recreated the script with TS and Clasp , check it out..
And regarding Automated Deploys there seems to be some issue with the clasp cli wherein you have to  [manually deploy the app](https://github.com/google/clasp/issues/63).

**Comment by nikhil-thakkar** [comment]
This is great. Swift migration. :tada:
Thanks. 
Will look into it.

**Pull request closed without merging**
